export const Bienes = [
    {
      id: 1,
      nombre: "LA CAROLINA ",
      ubicacion: "BOGOTA CUNDINAMARCA ",
      area: "84",
      habitaciones: "2",
      banos: "2",
      tipoInmueble: "APARTAMENTO EN ARRIENDO",
      precio: "250000000",
      parqueadero: "2",
      propietario: "JINETH CANO",
      descripcion:"Arriendo hermoso Apartamento. Ubicado en LA CAROLINA. Extraordinaria vista, séptimo piso exterior. Consta de sala - comedor con balcón amplio, espacio para estudio, alcoba principal con walking closet y baño, incluye espacio para star de TV, segunda alcoba comparte baño con el área social, cocina moderna con zona de lavaderia independiente.",
      image: "https://s3.amazonaws.com/imagenesprof.fincaraiz.com.co/OVFR_COL/2020/8/28/2617353_526_24.jpg",
    },
    {
      id: 2,
      nombre: "PUENTE LARGO ",
      ubicacion: "BOGOTA CUNDINAMARCA ",
      area: "68",
      habitaciones: "2",
      banos: "2",
      tipoInmueble: "APARTAMENTO EN ARRIENDO",
      precio: "1550000",
      parqueadero: "1",
      propietario: "JENNY SARMIENTO ",
      descripcion:"Apartamento en PUENTE LARGO, acogedor, tranquilo, encortinado, en perfecto estado, dos alcobas ambas con closet - la principal con dos closets - más cuarto estudio grande, sala-comedor, cocina integral a gas natural, cuarto de ropas, dos baños, calentador de paso eléctrico, parqueadero cómodo, depósito. Ubicado en tercer piso, sin ascensor.",
      image:  "https://s3.amazonaws.com/imagenes.fincaraiz.com.co/FC_COL/2022/10/25/7703430/apartamento-arriendo-cundinamarca-bogota-488991175.jpg"
    },   
    {
      id: 3,
      nombre: "SAN PATRICIO ",
      ubicacion: "BOGOTA CUNDINAMARCA ",
      area: "194",
      habitaciones: "4",
      banos: "2",
      tipoInmueble: "APARTAMENTO EN ARRIENDO",
      precio: "3200000",
      parqueadero: "3",
      propietario: "LAURA ARIZA  ",
      descripcion:"APARTAMENTO DUPLEX EN UN SEXTO PISO, DEMETROS CON UN ALTILLO DE 70 METROS, CUATRO ALCOBAS CON CLOSETH, CUARTO Y BAÑO DE SERVICIO, ESTUDIO, CUATRO BAÑOS, SALA COMEDOR CON CHIMENEA , GARAJE PARA TRES CARROS. DOS BALCONES Y TERRAZA . (se cambia el piso de alfombra por piso laminado)",
      image:  "https://s3.amazonaws.com/imagenesprof.fincaraiz.com.co/OVFR_COL/2022/11/24/3998683_155_6.jpg"
    },   
    {
      id: 4,
      nombre: "SANTA BARBARA  ",
      ubicacion: "BOGOTA CUNDINAMARCA ",
      area: "70",
      habitaciones: "2",
      banos: "2",
      tipoInmueble: "APARTAMENTO EN VENTA",
      precio: "710000000",
      parqueadero: "1",
      propietario: "MARIANA ARIZA  ",
      descripcion:"Sector exclusivo, quinto piso vista externa con altura de 2.55 mts, 2 habitaciones, 2 baños, 2 balcones, sala y comedor con cocina abierta, zona de lavado independiente, 1 parqueadero y 1 deposito, salón social, terraza bbq con chimeneas a gas, gimnasio, espacio libre para trx crossfit, vigilancia 24 horas.",
      image:  "https://s3.amazonaws.com/imagenesprof.fincaraiz.com.co/OVFR_COL/2022/9/5/3870705_707_6.jpg"
    },       
    {
      id: 5,
      nombre: " LA FELICIDAD  ",
      ubicacion: "BOGOTA CUNDINAMARCA ",
      area: "93",
      habitaciones: "3",
      banos: "2",
      tipoInmueble: "APARTAMENTO EN VENTA",
      precio: "550000000",
      parqueadero: "1",
      propietario: "INES PEREZ  ",
      descripcion:"Cuarto piso vista exterior, sala y comedor con balcón, cocina integral abierta, zona de lavandería, estudio, 3 habitaciones, 2 baños, parqueadero cubierto, deposito, conjunto con piscina, gimnasio, parque infantil, 2 salones sociales, zona bbq, vigilancia 24 horas",
      image:  "https://s3.amazonaws.com/imagenesprof.fincaraiz.com.co/OVFR_COL/2021/9/15/3314963_980_11.jpg"
    },        
    
    {
      id: 6,
      nombre: " MANDALAY ",
      ubicacion: "BOGOTA CUNDINAMARCA ",
      area: "220",
      habitaciones: "4",
      banos: "3",
      tipoInmueble: "CASA  EN VENTA",
      precio: "758000000",
      parqueadero: "1",
      propietario: "ALFREDO CANO  ",
      descripcion:"Casa en sector residencial muy tranquilo remodelada con amplios espacios cuenta con dos niveles en el primer nivel un garaje cubierto y otro exterior un estudio grande sala con chimenea baño social un segundo estudio comedor independiente cocina integral espacio de lavadora y secadora patio con zona verde en el segundo nivel cuatro habitaciones muy amplias una es la principal con baño privado vestier y balcon y dos habitaciones dobles con un baño que comparten. cerca a comercio y transporte..",
      image:  "https://s3.amazonaws.com/imagenesprof.fincaraiz.com.co/OVFR_COL/2020/12/11/53916550.jpg"
    },
    {
      id: 7,
      nombre: " ALAMOS",
      ubicacion: "BOGOTA CUNDINAMARCA ",
      area: "100",
      habitaciones: "3",
      banos: "2",
      tipoInmueble: "CASA  EN VENTA",
      precio: "328000000",
      parqueadero: "1",
      propietario: "JOSUE CANO",
      descripcion:"Amplia en conjunto cerrado tres niveles en el primero sala baño social comedor independiente cocina basica integral amplia pisos remodelados en ceramica segundo nivel dos habitaciones o estudio un baño principal patio grande con zona de lavanderia grande y ventilada tercer nivel encontramos habitacion principal muy amplia con closet pisos en madera laminada un garaje privado el conjunto cuenta con salones sociales zonas verdes espacio de BBQ cerca a diver plaza avenida mutis y comercio..",
      image:  "https://s3.amazonaws.com/imagenesprof.fincaraiz.com.co/OVFR_COL/2021/3/8/56972258.jpg"
    },
    {
      id: 8,
      nombre: " CEDRITOS ",
      ubicacion: "BOGOTA CUNDINAMARCA ",
      area: "35",
      habitaciones: "1",
      banos: "1",
      tipoInmueble: "APARTA ESTUDIO EN ARRIENDO",
      precio: "1400000",
      parqueadero: "1",
      propietario: "NATALIA LEAL",
      descripcion:"CEDRITOS. ARRIENDO hermoso Aparta estudio 35 M2. Ubicado en mejor sector de cedritos, tranquilo y residencial, ambientes separados, cocina tipo americano con lavandería, alcoba amplia con Vestier, baño con excelentes acabados, parqueadero cubierto, excelente zona con buenas vías de acceso, el edificio cuenta con seguridad 24/7",
      image:  "https://d3s5pkt10pk3ga.cloudfront.net/resizedImages/original/site/fincaraiz_service/media/listing/015088dc-d492-4807-af00-b7998f132029/photos/015088dc-d492-4807-af00-b7998f132029_1_True_b9e5e405-a9f5-4d21-9eee-84d117a69acd.jpg"
    },
    
    {
      id: 9,
        nombre: " MARLY ",
        ubicacion: "BOGOTA CUNDINAMARCA ",
        area: "30",
        habitaciones: "1",
        banos: "1",
        tipoInmueble: "APARTA ESTUDIO EN ARRIENDO",
        precio: "1280000",
        parqueadero: "1",
        propietario: "IVONNE CARDENAS",
        descripcion:"Hermoso apartaestudio en el cuarto piso del edificio. Excelente ubicación junto a la Clínica Marly a una cuadra de una estación de transmilenio, también tiene acceso por la cra 13 o la 7ma. El edificio cuenta con portería, vigilancia las 24 horas, ascensor y salón comunal. Ventilación y luz natural y espacios independientes habitación y zona social.",
        image:  "https://d3s5pkt10pk3ga.cloudfront.net/resizedImages/original/site/fincaraiz_service/media/listing/a37597a1-b7a5-42db-ac0c-1f5d26052f8a/photos/a37597a1-b7a5-42db-ac0c-1f5d26052f8a_1_True_7c78dd12-5afc-493c-bc98-b7179dc55041.jpeg"
      },
      {
        id: 10,
          nombre: " BOSTON",
          ubicacion: "MEDELLIN ANTIOQUIA ",
          area: "35",
          habitaciones: "1",
          banos: "1",
          tipoInmueble: "APARTA ESTUDIO EN ARRIENDO",
          precio: "750000",
          parqueadero: "COMUNAL",
          propietario: "JHON PEREZ",
          descripcion:"Excelente ubicación cerca a parques y biblioteca Leon de Greiff 1 alcoba zona de ropas parqueadero común carro",
          image:  "https://s3.amazonaws.com/imagenes.fincaraiz.com.co/FC_COL/2023/01/06/7843450/apartaestudio-arriendo-antioquia-medellin-504751727.jpg"
        },
  {
    id:11,
    nombre: "BELMIRA ",
    ubicacion: "BOGOTA CUNDINAMARCA",
    area: "35",
    habitaciones: "1",
    banos: "1",
    tipoInmueble: "APARTA ESTUDIO EN ARRIENDO",
    precio: "1150000",
    parqueadero: "1",
    propietario: "DANIEL CANO ",
    descripcion:" hermoso apartaestudio en piso 7 exterior con ascensor, no es mono ambiente, cocina semi-abierta, zona de lavandería independiente, garaje propio cubierto, vigilancia 24/7, estrato 4. Quedate con este hermoso apartaestudio, ubicado en lo mejor de Cedritos - Belmira, excelentes rutas de acceso, centros comerciales, comercio, ",
    image:  "https://s3.amazonaws.com/imagenesprof.fincaraiz.com.co/OVFR_COL/2022/12/16/4031121_778_0.jpg"
  },
  {
    id:12,
    nombre: "CEDRITOS ",
    ubicacion: "BOGOTA CUNDINAMARCA",
    area: "30",
    habitaciones: "1",
    banos: "1",
    tipoInmueble: "APARTA ESTUDIO EN VENTA",
    precio: "189000000",
    parqueadero: "1",
    propietario: "GERALDINE MARIN ",
    descripcion:"VENTA APARTAESTUDIO CEDRITOS (CAPRI)- Acogedor apartaestudio, remodelado, exterior, habitacion independiente, sala, escritorio, cocina abierta, 1 baño. Ubicado en segundo piso dentro de un tranquilo edificio en el hermoso sector de Capri, rodeado de parques y un ambiente residencial. Cuenta con un parqueadero propio cubierto en servidumbre y un deposito. ",    
    image:  "https://s3.amazonaws.com/imagenesprof.fincaraiz.com.co/OVFR_COL/2022/8/19/76423719.jpg"
  },
  {
    id:13,
    nombre: "SIBERIA ",
    ubicacion: "BOGOTA CUNDINAMARCA",
    area: "334",
    habitaciones: "4",
    banos: "4",
    tipoInmueble: "CASA EN ARRIENDO",
    precio: "6000000",
    parqueadero: "4",
    propietario: "KEVIN PINZON ",
    descripcion:"Entérate de todos los beneficios al arrendar con nosotros: Asistencia e intermediación con el propietario Firma tu contrato online Arrienda sin burocracia, sin papeleos ni notarías Casa en arriendo, ubicada en el barrio Chapinero Central, con una superficie construida de 334.00 m²",    
    image:  "https://s3.amazonaws.com/imagenesprof.fincaraiz.com.co/OVFR_COL/2022/10/18/79044289.jpg"
  },
  {
    id:14,
    nombre: "PRADO VERANIEGO ",
    ubicacion: "BOGOTA CUNDINAMARCA",
    area: "126",
    habitaciones: "3",
    banos: "3",
    tipoInmueble: "CASA EN ARRIENDO",
    precio: "2800000",
    parqueadero: "2",
    propietario: "VALENTINA SEVILLA ",
    descripcion:"Casa/apartamento bifamiliar en segundo piso de 90 metros construidos 2 habitaciones con baño c/u, tina. más otra habitación y/o estudio. Cocina integral a gas, sala con chimenea, comedor, patio en primer piso de 30 metros con zona de lavanderia y bbq. Calle cerrada con seguridad 24 horas.",    
    image:  "https://s3.amazonaws.com/imagenes.fincaraiz.com.co/FC_COL/2023/01/05/7840401/casa-arriendo-cundinamarca-bogota-503919474.jpg"
  },
  {
    id:15,
    nombre: "PRADO VERANIEGO ",
    ubicacion: "BOGOTA CUNDINAMARCA",
    area: "145",
    habitaciones: "0",
    banos: "1",
    tipoInmueble: "BODEGA EN ARRIENDO",
    precio: "2800000",
    parqueadero: "0",
    propietario: "SANTIAGO REYES",
    descripcion:"Bodega, con mezannine para oficina, luz trifásica, altura 5,60, portón 4,00 ancho x 5,00 alto. Negociable",    
    image:  "https://d3s5pkt10pk3ga.cloudfront.net/resizedImages/original/site/fincaraiz_service/media/listing/a6322b41-e713-4698-a3e9-4864e9302399/photos/a6322b41-e713-4698-a3e9-4864e9302399_1_True_8d370af1-79b7-4d48-8aee-8bda0fd95f19.jpeg"
  },
  {
    id:16,
    nombre: "FLORIDA BLANCA",
    ubicacion: "BOGOTA CUNDINAMARCA",
    area: "830",
    habitaciones: "0",
    banos: "4",
    tipoInmueble: "BODEGA EN ARRIENDO",
    precio: "18000000",
    parqueadero: "NO",
    propietario: "MONICA CIFUENTES",
    descripcion:"Bodega de dos pisos con terraza, doble altura y oficinas con ubicacion central y en perfectas condiciones para uso inmediato.",    
    image:  "https://d3s5pkt10pk3ga.cloudfront.net/resizedImages/original/site/fincaraiz_service/media/listing/4a66ffbe-3c11-42e0-956b-e459258f59ef/photos/4a66ffbe-3c11-42e0-956b-e459258f59ef_1_True_451502a2-622d-481f-9ef6-990cc6443ded.jpg" },
  {
    id:17,
    nombre: "LA ESTRADA  ",
    ubicacion: "BOGOTA CUNDINAMARCA",
    area: "350",
    habitaciones: "0",
    banos: "3",
    tipoInmueble: "BODEGA EN VENTA",
    precio: "1080000000",
    parqueadero: "0",
    propietario: "FELIPE SANTOS ",
    descripcion:"OFICINAS BODEGA con fácil acceso y a pocas cuadras amplio comercio, ubicadas cerca Clle. 68 - Avda. 68. Lote de 7x21.5 Mt2. PISO1 150,5 Mt2 altura máxima 2,30 Mt. con local o garajes, oficina, baño, y BODEGA 75 Mt2 altura 5,60 Mt. PISO2️ 97,5 Mt2 altura 2,40 Mt, con oficinas, baño. PISO3️ 97.5 Mt2 altura 2,60 Mt en una sola área, baño",    
    image:  "https://s3.amazonaws.com/imagenes.fincaraiz.com.co/FC_COL/2022/11/03/7726494/bodega-venta-cundinamarca-bogota-491527643.jpg"
  },
  {
    id:18,
    nombre: "SANTA LUCIA ",
    ubicacion: "BOGOTA CUNDINAMARCA",
    area: "620",
    habitaciones: "0",
    banos: "3",
    tipoInmueble: "BODEGA EN VENTA",
    precio: "2200000000",
    parqueadero: "0",
    propietario: "NESTOR CARRILLO ",
    descripcion:"Bodega con techo a dos aguas, estructura metálica y teja Eternit, con bigas de amarre y columnas en concreto, los pisos son en baldosa de tráfico pesado. El terreno total es de 19 x 25 de y la altura de la bodega principal es de 7.40mts, adicional tiene dos locales independientes en el primer piso de 17 x 3.5mts, cuenta con 3 baños.",    
    image:  "https://d3s5pkt10pk3ga.cloudfront.net/resizedImages/original/site/fincaraiz_service/media/listing/d167bb0b-e2e9-47e9-854b-a011753b9fc0/photos/d167bb0b-e2e9-47e9-854b-a011753b9fc0_1_True_cca10043-7cfb-47bb-a17e-c5bcd5b94904.jpg"
  },
]
